module.exports = {
  GLOBAL_CHAT:"GLOBAL_CHAT",
	USER_CONNECTED:"USER_CONNECTED",
	MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
	MESSAGE_SENT:"MESSAGE_SENT",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	TYPING:"TYPING",
	PRIVATE_MESSAGE:"PRIVATE_MESSAGE",
	NEW_CHAT_USER: "NEW_CHAT_USER",
	GLOBAL_CHAT_ID: "GLOBAL_CHAT_ID"
}